POST http://localhost:8000/api/game/
Content-Type: application/json

{"player": "X"}

> {%
   client.global.set("gameId", response.body.id);
 %}

###

PUT http://localhost:8000/api/game/
Content-Type: application/json

{"gameId": "{{gameId}}", "player": "X", "position": 1}

###

GET http://localhost:8000/api/game/{{gameId}}
Accept: application/json

> {%
   client.global.set("stepId", response.body.game.history[0]);
 %}

###

GET http://localhost:8000/api/game?offset=0&limit=1
Accept: application/json

###

GET http://localhost:8000/api/game/step/{{stepId}}
Accept: application/json

###